server:
  servlet:
    session:
      timeout: 60  # 기본값은 30m(30분) m을 붙이지 않으면 초단위로 설정됨. 최소 60초 이상일 것
      tracking-modes: cookie  #최초접속 시 url에 jsession안붙게

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/usedbook
    driver-class-name: org.mariadb.jdbc.Driver
    username: usedbookroot
    password: 1234

mybatis:
  type-aliases-package: thwjd.usedbook.domain
  mapper-locations: mybatis/**.xml


## mapper.xml 위치 지정
#mybatis.mapper-locations: mybatis-mapper/**/*.xml
#
## model 프로퍼티 camel case 설정
#  mybatis.configuration.map-underscore-to-camel-case=true
#
#  # 패키지 명을 생략할 수 있도록 alias 설정
#  mybatis.type-aliases-package=com.azurealstn.codespringweb.domain
#
#  # mapper 로그레벨 설정
#  logging.level.com.azurealstn.codespringweb.mapper=TRACE

